### ISSUE TITLE
Error when running the code

### ISSUE THREAD

**Issue by razvanc92** [Luoyonghong/E2EGAN#2]
Hello, I've tried to run the code and I'm receving the following error:

"..imputation/E2EGAN_PHY.py", line 223, in time_series_to_z
    init_state = self.grui_cell_g1.zero_state(self.batch_size, dtype=tf.float32) # 初始化全零 state
AttributeError: 'E2EGAN' object has no attribute 'grui_cell_g1'

Any ideas how to fix it?

**Comment by Luoyonghong** [comment]
Seems your tensorflow version dont match, what's your version? Could you paste the full error logs?

**Comment by razvanc92** [comment]
You're right. It was a problem with my TF version.

**Comment by mikerq** [comment]
hello, can E2EGAN fill in missing values of univariate time series?

**Comment by mikerq** [comment]
Hello, I want to predict the water level only by the water level. Can you help me fill in the missing value of water level with E2EGAN?

**Comment by mikerq** [comment]
I tried to understand E2EGAN by running through your code, but it seems that I reported a lot of errors.
