### ISSUE TITLE
关于Kdd数据集的一些问题

### ISSUE THREAD

**Issue by zhumorui** [Luoyonghong/E2EGAN#5]
你好，请问在您的代码中，我好像没有找到关于Kdd数据集运行的代码，请问能分享一下吗？

**Comment by huweiv** [comment]
你好，请问你收到了关于Kdd数据集运行的代码了吗？

**Comment by thanhquanse** [comment]
Hello,

I am also waiting for the KDD code implementation to be shared. Does anyone receive it?
Thanks!
